### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by pjai0005** [yuwei217/ETC5513_assignment4_team_Nemo#2]
Can we show a world map in the introduction of our analysis?

**Comment by Sithajawahar** [comment]
Yes, but which packages do I need to install for that and where are we going to refer to, for the code ?

**Comment by yuwei217** [comment]
We can refer StackOverflow or any other website.

**Comment by pjai0005** [comment]
\section*{Introduction}

```{r, fig.cap = "Top Three Trading Economies in the World",
out.width="100%", fig.show="hold", out.width="100%"}
final<- read.csv("data/team_nemo.csv")
library(maptools)
    data(wrld_simpl)
    myCountries = ***@***.***$NAME %in% c("China", "Germany", "United
States")
    plot(wrld_simpl, col = c(gray(.8), "red")[myCountries+1])
```
Given the recent Suez Canal fiasco, many countries were facing severe
problems in trade markets. Which made us all curious to dive deeper into
the subject.

For our analysis we will compare the export and import patterns over a span
of 3 years. And according to World Statistical Review 2019, the countries
that we have chosen are taken as the top three global trading economies.

For our analysis we are comparing the export and import patterns of these
countries over a span of three years to see if they have an import or
export deficit, if so, which sector is causing the same. Sectors where they
have good in- house production and where they need the materials from other
countries.

\section*{Germany}

```{r}

germany <- final %>% filter(Country == "Germany")
germany_import <- germany %>% filter(Flow == "Import")
germany_export <- germany %>% filter(Flow == "Export")

```

Germany is the most powerful economy of Europe with the biggest export
commodities as automobiles and medicament. Besides, we all are aware of the
fact that Germany exports a large number of automobiles and their parts to
different countries. But did you know that for Germany, the import of
automobiles also plays an important role in its trade markets? This can be
seen through the below graph:


```{r}

a<- germany%>% mutate(Trade = Trade/1000000000) %>%
  filter(Category %in% c("rubber", "cars", "coffee", "pharma",
"iron_steel"))%>%
    ggplot(aes(x = reorder(Category, -Trade),
 y = Trade, fill = Flow)) +
 geom_col(position = "dodge")+
  scale_y_continuous(labels=scales::dollar_format())+
 scale_fill_brewer(palette = "Dark2") +
 facet_grid(~ Year)+
  xlab("Trade in Billions")+
  labs(title = "Top Five Traded Goods")+
    theme(axis.title.x=element_blank(),
          axis.text.x= element_text(angle = 25))

b<- germany %>% mutate(Trade = Trade/1000000000) %>%
  filter(Category %in% c("tobacco", "fruits_nuts", "cotton", "sugar",
"wheat"))%>%
    ggplot( mapping = aes(x = reorder(Category, -Trade),
 y = Trade, fill = Flow)) +
 geom_col(position = "dodge") +
  scale_y_continuous(labels=scales::dollar_format())+
 scale_fill_brewer(palette = "Set1") +
 facet_grid(~Year)+
  xlab("Trade in Billions")+
  labs(title = "Least Five Traded Goods")+
    theme(axis.title.x=element_blank(),
          axis.text.x= element_text(angle = 25))

```

```{r gtrade, fig.cap = "Traded Goods in germany", out.width="100%",
fig.show="hold", out.width="100%"}
ggarrange(a, b, legend = "top",
          ncol =1, nrow = 2)
```
The first section of figure ***@***.***(fig:gtrade) shows the five most traded
goods of Germany where one can see that the Automobiles sector indeed has
more Export value than any other sector taken into consideration. However,
the import value of Pharmaceuticals is higher than that of Automobiles. The
trade value can be seen rising from 2016 to 2018 for Automobiles and
Pharmaceuticals. Along with these, commodities like Coffee and Iron_Steel
are exported more than what is being exported. For Rubber, the difference
in export and import values isn't much significant.


The same figure (figure ***@***.***(fig:gtrade)) shows the least traded
commodities in Germany. Tobacco consistently sees a downfall in its export
value however its import value contradicts by rising for the given years.
Just like Rubber in the first section of the graph, the import and export
value of cotton is almost the same. Unlike any other commodity, fruits and
nuts have much higher import value.

```{r germanytrend}

itrade_val <- germany_import %>% rename("Import_Value"= Trade,
                                        "Import"= Flow)

etrade_val <- germany_export %>% rename("Export_Value"= Trade,
                                        "Export"= Flow)

trade <- itrade_val %>%
  left_join(etrade_val, by=c("Year"="Year",
                            "Country"= "Country",
                            "Category"= "Category"))

mean_tarde<- trade %>%
  group_by(Year)%>%
    summarise(Ex_Value= mean(Export_Value),
              Im_Value=mean(Import_Value)) %>%
  mutate(Mean_Trade = Ex_Value + Im_Value) %>%
  select(Year, Mean_Trade)


 knitr::kable(mean_tarde, caption = "Trend of Trade in Germany") %>%
    kable_styling (latex_options = c("hover", "hold_position"))

```

Table ***@***.***(tab:germanytrend) shows the mean value by Year of all the
commodities traded in Germany. The table displays that the Trade value
(Export value and Import Value) for 2016 is about 700 million USD. This
increases by about 100 million more in the year 2017. And for 2018, it is
nearly about 900 million USD. Hence the trade over these years has seen
quite a bit increase.


```{r germanycomo}

trend<- trade%>%
  group_by(Category)%>%
    summarise(Ex_Value= mean(Export_Value),
              Im_Value= mean(Import_Value)) %>%
  mutate(Trend = Ex_Value - Im_Value) %>%
  arrange(-Trend)


 knitr::kable(trend, caption = "Traded Comodities in Germany") %>%
    kable_styling (latex_options = c("striped", "hold_position"))%>%
   kable_classic()


```

From table ***@***.***(tab:germanycomo) can be observed, net trading can be
observed in the table. Where there are more exports (positive values) than
Imports (negative values) making this a largely export-oriented country.
Automobiles and Medicament contributing the most while Coffee and Iron &
Steel contributing very less. Fruits and Nuts rank the lowest as it's
imported in much higher value than what it is being exported.
From the table, cars are exported at the highest rate of 1.89 Billion and
cotton is imported the most.
